### ISSUE TITLE
Doesn't work on wayland.

### ISSUE THREAD

**Issue by magnus-ISU** [Kirottu/arch-wiki-dmenu#1]
You could fix this by changing the script to the following:

```
#!/bin/bash

dmenu=dmenu
wayland=`loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'`
[[ $wayland = wayland ]] && dmenu="fuzzel -d"

opener=xdg-open
type $opener >/dev/null || opener=surf

WIKI_PATH=/usr/share/doc/arch-wiki/html/en

WIKI_SEARCH=$(du -a $WIKI_PATH | cut -f2 | cut -d/ -f8 | sed 's/.html//g' | $dmenu -i)
WIKI="$WIKI_PATH/$WIKI_SEARCH.html"

if [ -n "$WIKI_SEARCH" ]; then
        $opener $WIKI
fi
```

Then you need to have `fuzzel` installed for wayland support.

I see you maintain it on the AUR as well. It would be awesome if you could add this there and add a dependency for `xdg-utils` rather than surf since `xdg-open` will work for anyone.

**Comment by Kirottu** [comment]
Wow, I forgot that this even existed. I have not touched this in years, but makes sense that it doesn't work on wayland due to surf and dmenu, if you want to fix it feel free to make a PR with those changes.
